### ISSUE TITLE
reload(sys) drops stdio mappings

### ISSUE THREAD

**Issue by JCobeyTanium** [tanium/pytan#14]
Discovered this issue when trying to use pytan with Project Jupyter. This is not really a bug, but in https://github.com/tanium/pytan/blob/master/lib/pytan/sessions.py
lines 39-41

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

The reload(sys) kills off any stdio mappings that a user sets before the user loads pytan. It is a known issue
https://github.com/ipython/ipython/issues/8354
http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script

There is a suggested fix of saving the stdio before reloading. Something like.

default_stdout = sys.stdout
default_stderr = sys.stderr
reload(sys)
sys.stdout = default_stdout
sys.stderr = default_stderr

**Comment by lifehackjim** [comment]
In 4.0.0 that sys reload goes away, and will no longer present an issue. Setting the default encoding like that is a "Pretty Bad Hack(tm)" to handle improperly encoded XML responses. I'm solving this better in 4.0.0.
