### ISSUE TITLE
Deploy Action throws RBAC error

### ISSUE THREAD

**Issue by Robiq** [tanium/pytan#54]
With the release of the new version (7.2), all action deployments throw RBAC errors when retrieving results. It is also no longer possible to deploy actions without specifying an action group.

When not specifying an action group, this error is displayed:
https://gist.github.com/Robiq/5a4b4efc325bdf4d00a839b49231b961

When specifying an action group, this error is displayed:
https://gist.github.com/Robiq/a975bd9ea8df42aea4997d6d00070090

Both of these are when logged in as an administrator with no restrictions.
If possible, a hotfix or temporary hack would be great, so that regular operations can be resumed.
Thank you!

**Comment by lifehackjim** [comment]
A few questions: 
 - can you supply the snippet of python code that you are using to trigger the error received when specifying an action group?
 - can you supply the name of the package you are attempting to deploy?

I will endeavor to reproduce this behavior.

**Comment by lifehackjim** [comment]
I'm unable to reproduce this with pytan 2.2.2 against Tanium 7.2.314.3181, here are my steps:

`
# ensure we can get the package object we intend to use:
pkg_obj = handler.get("package", name="Custom Tagging - Add Tags")[0]
print(pkg_obj)
'''
PackageSpec, name: 'Custom Tagging - Add Tags', id: 53
'''

# fetch the user object for the current user:
session_id = handler.session.session_id
user_id = session_id.split("-")[0]
user_obj = handler.get("user", id=user_id)[0]
print(user_obj)
'''
User, name: 'Administrator', id: 1
'''

# try to run the package with NO action group (fails appropriately):
deploy_ret = handler.deploy_action(package="Custom Tagging - Add Tags{$1=moo}", run=True)
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jim.olsen/Downloads/pytan-2.2.2/lib/pytan/handler.py", line 978, in deploy_action
    **clean_kwargs
  File "/Users/jim.olsen/Downloads/pytan-2.2.2/lib/pytan/handler.py", line 3103, in _deploy_action
    added_objs = self._add(obj=add_objs, pytan_help=h, **clean_kwargs)
  File "/Users/jim.olsen/Downloads/pytan-2.2.2/lib/pytan/handler.py", line 2313, in _add
    raise pytan.exceptions.HandlerError(err(search_str, e))
pytan.exceptions.HandlerError: Error while trying to add object 'SavedAction, name: 'API Deploy Custom Tagging - Add Tags', id: -1': Response command SOAP Processing Exception: AddSavedActionFailed: Adding the saved action failed.  Must specify action group or action group id. does not match request command AddObject!!
'''

# fetch the action group we want to use:
grp_obj = handler.get("group", name="Test1")[0]
# export the object into json format to see all the attributes. we can see here that Test1 targets the computer group "All Computers":
print(handler.export_obj(grp_obj, "json"))
'''
{
  "_type": "group",
  "and_flag": 0,
  "deleted_flag": 0,
  "filters": {
    "_type": "filters",
    "filter": []
  },
  "id": 78,
  "name": "Test1",
  "not_flag": 0,
  "sub_groups": {
    "_type": "groups",
    "group": [
      {
        "_type": "group",
        "and_flag": 1,
        "deleted_flag": 0,
        "filters": {
          "_type": "filters",
          "filter": []
        },
        "id": 1,
        "name": "All Computers",
        "not_flag": 0,
        "sub_groups": {
          "_type": "groups",
          "group": [
            {
              "_type": "group",
              "id": 0
            }
          ]
        },
        "type": 0
      }
    ]
  },
  "type": 1
}

'''
# try to run the package with an action group (times out, but does run appropriately):
deploy_ret = handler.deploy_action(package="Custom Tagging - Add Tags{$1=moo}", run=True, action_group="Test1")
'''
2018-07-10 15:41:20,600 WARNING  pytan.pollers.ActionPoller: ID 7: Reached expiration timeout of 2018-07-10T15:41:20
'''
`

**Comment by Robiq** [comment]
Thank you so much for your assistance! After debugging more, it seems something happened to the content sets and access rights of our scripts during update, causing the issue.

I'm sorry for taking up your time, when it turned out the issue was on our end!

**Comment by Robiq** [comment]
Thank you so much for your assistance!
After debugging more, it seems something happened to the content sets and access rights of our scripts during update, causing the issue.

I'm sorry for taking up your time, when it turned out the issue was on our end!

**Comment by lifehackjim** [comment]
No worries at all, glad I could help.
